### ISSUE TITLE
help me teacher

### ISSUE THREAD

**Issue by chaewonKim98** [2021-SMHRD-KDT-Bigdata-4/coffee#44]
저희가 자바에서 머신러닝으로 값을 보내고 머신러닝에서 추천해준 원두를 url에 컨트롤러를 써서 자바 컨트롤러로 받으려고 합니다. 컨트롤러에서 어떻게 받는지와 db에 저장을 할 때 spl문을 어디에 써줘야 하는지 궁금 합니다.
아직 툴과 컨트롤러가 만들어지지 않았는데 test를 해보고 싶어서입니다!!

**Comment by CHOI-sw123** [comment]
플라스크 - 서블릿 연동 PPT 그림 설명
