### ISSUE TITLE
help me 썬생님 ㅠ

### ISSUE THREAD

**Issue by chaewonKim98** [2021-SMHRD-KDT-Bigdata-4/coffee#47]
html 코드에서 한페이지에 5개의 설문을 받을떄 각 문항에서 한개만 선택할 수 있도록 라디오버튼을 넣었는데 하나를 1문제를 체크하고 다른문제를 체크했을때 체크를 해뒀던 곳이 풀립니다! 
근아씨 자리에서 확인부탁드립니다 ㅠ ㅅ ㅠ

**Comment by CHOI-sw123** [comment]
각 문항의 라디오 버튼들의 name을  다르게 설정
모든 라디오 버튼들의 name이 같았음
