### ISSUE TITLE
help me teacher

### ISSUE THREAD

**Issue by chaewonKim98** [2021-SMHRD-KDT-Bigdata-4/coffee#54]
자바에서 플라스크를 통해서 파이썬으로 값이 넘어가는것 까지는 확인이 되는데 보내줄때가 않됩니다....

**Comment by princehd** [comment]
- 리다이렉션시 포트번호 잘못 설정
- VO객체 생성 후 필드 초기화 x -> Mybatis 에러
- 쿼리스트링 파라미터 이름과 request 객체에서 얻어내는 파라미터 이름이 다름
